export default {
  publicTransit: {
    nav: '公开资料', title: '公开中转资料', subtitle: '标准化公开模型价格、充值倍率、模型分组倍率与可用性监测。',
    backHome: '返回首页', backToSettings: '返回公开资料设置', adminPreview: '后台预览：以下内容与公开资料页保持一致', copyDiscovery: '复制发现接口', copyEndpoint: '复制公开接口', copySnapshot: '复制 V1 快照', copySnapshotV2: '复制 V2 快照', disabledTitle: '公开资料出口未启用', disabledDesc: '站点管理员需要先在系统设置中启用公开资料出口。',
    rechargeRatio: '充值倍率', groups: '公开分组', models: '模型数量', generatedAt: '生成时间', modelPricing: '模型价格', modelPricingHint: '价格按 $/MTok 和 $/request 展示，内部账号信息不会公开。',
    searchPlaceholder: '搜索分组或模型', allPlatforms: '全部平台', allGroups: '全部分组', allModels: '全部模型', resetFilters: '重置', group: '分组', model: '模型', multiplier: '倍率', billingMode: '计费模式', billingToken: '按 token', billingPerRequest: '按次', availability: '可用性', priceSource: '价格来源', priceSourceCustom: '自定义', priceSourceStandard: '标准库', priceSourceUnknown: '未知',
    inputPrice: '输入价 / MTok', outputPrice: '输出价 / MTok', cachePrice: '缓存价', cacheInputPrice: '缓存输入价 / MTok', cacheCreatePrice: '缓存创建价 / MTok', cacheCreate: '缓存创建', cacheHit: '缓存命中', cacheHitRate: '缓存命中率', totalCacheHitRate: '累计缓存命中率', last24h: '24h', last7d: '7天', total: '累计', perRequestPrice: '按次/尺寸价',
    emptyModels: '暂无公开模型价格', emptyGroupModels: '该分组暂未公开具体模型清单', monitoring: '可用性监测', monitoringHint: '公开模型状态、延迟、可用率与最近时间线。', emptyMonitoring: '暂无公开监测数据', monitoringModeV1: 'V1 主动探测模式', monitoringModeV2: 'V2 被动监控模式', monitoringSummary: '公开监控指标摘要', passiveMonitoring: 'V2 被动监控', passiveMonitoringHint: '基于匿名聚合的真实请求数据，仅展示公开汇总指标。', passiveSource: '数据来源：匿名聚合真实请求', passivePrivacyHint: '不包含用户、账号、密钥、Cookie 或内部渠道信息。', passiveEnabled: '正在采集', passiveUnavailable: '暂无样本', passiveUnavailableDesc: '当前部署暂时无法提供真实流量聚合数据。', passiveRequests: '请求数', passiveSuccessRate: '成功率', passiveErrorRate: '错误率', passiveAvgLatency: '平均延迟', passiveAvgTTFT: '平均首 token', passiveCacheRate: '缓存率', passiveCacheHint: '按当前时间窗口聚合', passiveRPM: 'RPM', passiveRPMHint: '每分钟请求数', passiveWindowLabel: '数据窗口', passiveRange: '时间范围', passiveRanges: { '90m': '90m', '24h': '24h', '7d': '7d', '30d': '30d' }, passiveMetric: '指标维度', passiveMetrics: { overall: '综合', error: '错误率', ttft: '首 Token', cache: '缓存率' }, passiveGroupsTab: '平台 / 分组', passiveModelsTab: '模型', passiveDimensionTitle: '平台 / 分组维度', passiveDimensionHint: '按平台与分组对比成功率、错误率、首 Token、延迟与请求量。', passiveTimelineTitle: '可用性趋势', passiveTimeline: '按时间查看分组健康状态', passiveBucketMinutes: '{count} 分钟粒度', passiveBucketHours: '{count} 小时粒度', passiveBucketDays: '{count} 天粒度', passiveBad: '差', passiveGood: '好', passiveHealthy: '健康', passiveWarning: '需关注', passiveCritical: '异常', passiveNoTraffic: '无流量 / 样本不足', passiveDimension: '监控维度', passiveEmpty: '当前筛选窗口暂无可公开的聚合样本', lastRequest: '最近请求', platform: '平台', disclosure: '来源披露', upstreamType: '上游类型', accountPoolType: '账号池', cacheSupported: '缓存计费', completeness: '准入完整度', hasRechargeRatio: '充值倍率', hasGroupMultipliers: '分组倍率', hasModelPricing: '模型价格', hasMonitoring: '可用性', hasSourceDisclosure: '来源披露', publicNote: '仅展示可公开的价格、倍率、缓存与可用性数据，不公开账号、密钥、Cookie 或内部渠道 ID。'
  }
}
