export default {
  publicTransit: {
    nav: 'Public Data', title: 'Public Transit Data', subtitle: 'Standard public model pricing, recharge ratio, group multipliers and availability monitoring.',
    backHome: 'Back home', backToSettings: 'Back to public data settings', adminPreview: 'Admin preview: this view mirrors the public data page', copyDiscovery: 'Copy discovery URL', copyEndpoint: 'Copy public endpoint', copySnapshot: 'Copy V1 snapshot', copySnapshotV2: 'Copy V2 snapshot', disabledTitle: 'Public transit export is disabled', disabledDesc: 'An administrator needs to enable the public transit export in settings.',
    rechargeRatio: 'Recharge ratio', groups: 'Public groups', models: 'Models', generatedAt: 'Generated at', modelPricing: 'Model pricing', modelPricingHint: 'Prices are shown as $/MTok and $/request. Private account details are never exposed.',
    searchPlaceholder: 'Search group or model', allPlatforms: 'All platforms', allGroups: 'All groups', allModels: 'All models', resetFilters: 'Reset', group: 'Group', model: 'Model', multiplier: 'Multiplier', billingMode: 'Billing mode', billingToken: 'Token', billingPerRequest: 'Per request', availability: 'Availability', priceSource: 'Price source', priceSourceCustom: 'Custom', priceSourceStandard: 'Standard', priceSourceUnknown: 'Unknown',
    inputPrice: 'Input / MTok', outputPrice: 'Output / MTok', cachePrice: 'Cache', cacheInputPrice: 'Cache input / MTok', cacheCreatePrice: 'Cache create / MTok', cacheCreate: 'Cache create', cacheHit: 'Cache hit', cacheHitRate: 'Cache hit rate', totalCacheHitRate: 'Total cache hit rate', last24h: '24h', last7d: '7d', total: 'Total', perRequestPrice: 'Request / size',
    emptyModels: 'No public model pricing yet', emptyGroupModels: 'This group has no public model catalog yet', monitoring: 'Availability monitoring', monitoringHint: 'Model status, latency, availability and recent timeline.', emptyMonitoring: 'No public monitoring data yet', monitoringModeV1: 'V1 active probe mode', monitoringModeV2: 'V2 passive monitoring mode', monitoringSummary: 'Public monitoring summary', passiveMonitoring: 'V2 passive monitoring', passiveMonitoringHint: 'Anonymous aggregates from real requests. Only public summary metrics are shown.', passiveSource: 'Source: anonymous real-request aggregates', passivePrivacyHint: 'No users, accounts, keys, cookies or internal channel details are included.', passiveEnabled: 'Collecting', passiveUnavailable: 'No samples', passiveUnavailableDesc: 'Real-traffic aggregates are not available on this deployment yet.', passiveRequests: 'Requests', passiveSuccessRate: 'Success rate', passiveErrorRate: 'Error rate', passiveAvgLatency: 'Avg latency', passiveAvgTTFT: 'Avg TTFT', passiveCacheRate: 'Cache rate', passiveCacheHint: 'Aggregated for the selected window', passiveRPM: 'RPM', passiveRPMHint: 'Requests per minute', passiveWindowLabel: 'Data window', passiveRange: 'Time range', passiveRanges: { '90m': '90m', '24h': '24h', '7d': '7d', '30d': '30d' }, passiveMetric: 'Metric dimension', passiveMetrics: { overall: 'Overall', error: 'Error rate', ttft: 'First Token', cache: 'Cache rate' }, passiveGroupsTab: 'Platform / group', passiveModelsTab: 'Models', passiveDimensionTitle: 'Platform / group dimensions', passiveDimensionHint: 'Compare success, error, first-token, latency and request volume by platform and group.', passiveTimelineTitle: 'Availability trend', passiveTimeline: 'Group health by time bucket', passiveBucketMinutes: '{count}-minute buckets', passiveBucketHours: '{count}-hour buckets', passiveBucketDays: '{count}-day buckets', passiveBad: 'Bad', passiveGood: 'Good', passiveHealthy: 'Healthy', passiveWarning: 'Watch', passiveCritical: 'Critical', passiveNoTraffic: 'No traffic / insufficient samples', passiveDimension: 'Monitor dimension', passiveEmpty: 'No public aggregate samples match the current filters', lastRequest: 'Last request', platform: 'Platform', disclosure: 'Disclosure', upstreamType: 'Upstream type', accountPoolType: 'Account pool', cacheSupported: 'Cache pricing', completeness: 'Admission completeness', hasRechargeRatio: 'Recharge ratio', hasGroupMultipliers: 'Group multipliers', hasModelPricing: 'Model pricing', hasMonitoring: 'Availability', hasSourceDisclosure: 'Source disclosure', publicNote: 'Only public pricing, multipliers, cache and availability data are shown. Accounts, keys, cookies and internal channel IDs are never exposed.'
  }
}
